export type ProductRow = {
  sku: string;
  name: string;
  category: string;
  unit: string;
  status: "In stock";
};

export const PRODUCT_CATEGORIES = ["Fibre connectivity", "Enclosures and termination", "Tools and consumables", "Cables", "Active networking", "Aerial hardware"] as const;

export const PRODUCT_ROWS: ProductRow[] = [
  { sku: "ECA-001", name: "FIBER Sleeves", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-002", name: "4U Cabinet", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-003", name: "FIBER Toolkit", category: "Tools and consumables", unit: "Kit", status: "In stock" },
  { sku: "ECA-004", name: "6 Core Drop Cable 2KM", category: "Cables", unit: "Reel", status: "In stock" },
  { sku: "ECA-005", name: "Fibreglass Ladder 12 By 2 Steps", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-006", name: "6U Cabinet", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-007", name: "Glk Power Meter", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-008", name: "Adapter Boxes 255BY200BY80", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-009", name: "Gm 630 XPON ZTE Dual Band", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-010", name: "Adapter Duplex LC UPC", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-011", name: "GPON HG8546M Router Single Band", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-012", name: "Adapter Sc/apc", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-013", name: "GPON Router EG8145V5 Dual Band", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-014", name: "Adapter Scupc", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-015", name: "Hikvision 300MBPS", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-016", name: "ADSS 12 Core G652D 60M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-017", name: "Hioso 4 Port EPON OLT", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-018", name: "ADSS 24 Core G652D 60M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-019", name: "HSGQ 4GE X400DW Router - Dual Band", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-020", name: "ADSS 24C 100M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-021", name: "HSGQ OLT GPON 1 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-022", name: "ADSS 48 Core G652D 100M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-023", name: "HSGQ OLT GPON 2 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-024", name: "ADSS 96C 100M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-025", name: "HSGQ OLT GPON 4 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-026", name: "ATB Empty", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-027", name: "HSGQ OLT GPON 8 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-028", name: "ATB Loaded LC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-029", name: "HSGQ SFP 10G 20KM Pair", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-030", name: "ATB Loaded SC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-031", name: "HSGQ XPON 1 Ge 1GE + 2.4G X100W3", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-032", name: "Banding Tool", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-033", name: "HSGQ XPON 1 Ge Onu Bridge", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-034", name: "Bare Splitter 1 By 16", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-035", name: "Insulating Tape Windsor 20Y", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-036", name: "Bare Splitter 1 By 2", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-037", name: "Jhook Big (10 -15MM)", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-038", name: "Bare Splitter 1 By 4", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-039", name: "Jhook SMALL(8-12MM)", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-040", name: "Bare Splitter 1 By 8", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-041", name: "Laser Pen", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-042", name: "Black Tape", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-043", name: "Media Converter Base 1000 HSGQ", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-044", name: "Buckle C201", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-045", name: "Mercusys Wireless Router MW306R", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-046", name: "Buckle Small", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-047", name: "Mikrotik RB951", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-048", name: "Buffer Tube 20M", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-049", name: "Mikrotik L009-RM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-050", name: "Buffer Tube 50M", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-051", name: "Mikrotik RB40111", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-052", name: "Cable Clip 9MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-053", name: "Mini ADSS 6C 80M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-054", name: "Cable Clip 8MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-055", name: "Mini ADSS 8 Core 80M Span", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-056", name: "Cable Clips 9MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-057", name: "Mini OTDR NK4000", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-058", name: "Cable Slitter", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-059", name: "Nanostation Ubiquiti M2", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-060", name: "Cable Storage Galvanized", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-061", name: "Netis Router Wireless", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-062", name: "Cable Stripper", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-063", name: "ODF 12 Core SC UPC Loaded", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-064", name: "Cable Ties 100MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-065", name: "ODF 24 Core SC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-066", name: "Cable Ties 150MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-067", name: "ODF 24C Lc/upc", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-068", name: "Cable Ties 250MM", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-069", name: "ODF 24C Sc/upc", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-070", name: "CAT 6 Indoor Adl", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-071", name: "ODF 48 Core LC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-072", name: "Cleaver S09", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-073", name: "ODF 48 Core SC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-074", name: "Climber Straps", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-075", name: "ODF 96 Core LC UPC", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-076", name: "Clipping Tool Green", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-077", name: "Optical FIBER Identifier", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-078", name: "Clipping Tool Passthrough", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-079", name: "Patchcord LC UPC SC APC Duplex 1M", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-080", name: "Closure Tray", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-081", name: "Patchcord LC UPC SC UPC Duplex 1M", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-082", name: "Concrete Climbers With Strap", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-083", name: "Patchcord SC UPC SC APC 1M Simplex", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-084", name: "Crimping Tool With Tester", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-085", name: "Patchcord SC UPC SC UPC 1M Simplex", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-086", name: "D006 12C Dome Closure - Heatshrink", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-087", name: "Patchcord Sc/upc Sc/upc 2M", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-088", name: "D008 - 24C Dome Type Closure, Mechanical - Red Ribbon", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-089", name: "PDU 6 Way", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-090", name: "D008 - 48C Dome Type Closure, Mechanical - Red Ribbon", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-091", name: "Pigtail LC UPC Yellow SM 0.9MM", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-092", name: "Pigtail SC APC Yellow SM 0.9MM", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-093", name: "D008 Dome Closure 48CORE Red Ribbon", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-094", name: "Pigtails LC APC Green", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-095", name: "D008 Dome Enclosure 24 Core Red Ribbon", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-096", name: "Pigtails Lc/apc", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-097", name: "Data Cabinet 12U", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-098", name: "Pigtails Sc/upc", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-099", name: "Dome Closure 24 Core (red Ribbon)", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-100", name: "Power Metre From Toolkit", category: "Tools and consumables", unit: "Kit", status: "In stock" },
  { sku: "ECA-101", name: "Dome Closure 48 Core (red Ribbon)", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-102", name: "Preforms 6-7 MM", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-103", name: "Dome Closure 48 Core Onsite", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-104", name: "Preforms 9-10MM", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-105", name: "Dome Closure 96 Core (red Ribbon)", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-106", name: "Reverse POE Switch", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-107", name: "Dome Closure D006 12 Core", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-108", name: "RJ45 Connectors", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-109", name: "Downlead Clamp With Strap", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-110", name: "Ruijie 6262G", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-111", name: "Drop Cable (2 Core) 1KM", category: "Cables", unit: "Reel", status: "In stock" },
  { sku: "ECA-112", name: "Safety Harness", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-113", name: "Drop CABLE(2 Core) 2KM", category: "Cables", unit: "Reel", status: "In stock" },
  { sku: "ECA-114", name: "Safety Harness 2026", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-115", name: "Dual Band XPON EG8145", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-116", name: "Sc/upc Adapters", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-117", name: "Dual Face Plate With Modules", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-118", name: "Single Faceplate With Modules", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-119", name: "EAP110 Indoor Access Point", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-120", name: "Sleeves", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-121", name: "EAP110 Outdoor Access Point", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-122", name: "Splitter 1 By 16 SC APC (green) With Connectors", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-123", name: "ECA CAT 6 Indoor Cable", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-124", name: "Splitter 1 By 16 SC UPC (blue) With Connectors", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-125", name: "ECA CAT 6 Outdoor Cable", category: "Cables", unit: "Each", status: "In stock" },
  { sku: "ECA-126", name: "Steel Strap 30M", category: "Aerial hardware", unit: "Roll", status: "In stock" },
  { sku: "ECA-127", name: "F102 Dome Closure 48 Core", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-128", name: "Steel Strap 50M Roll", category: "Aerial hardware", unit: "Roll", status: "In stock" },
  { sku: "ECA-129", name: "F102M Dome 24CORE", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-130", name: "Steel Straps 50M Small", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-131", name: "F102M Dome Closure 24C", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-132", name: "Storage Brackets (galvanized)", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-133", name: "F102M Dome Closure 48C", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-134", name: "Straps For Climbers", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-135", name: "F680 ZTE Router GPON Dual Band", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-136", name: "Switch 8 Port Tenda", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-137", name: "Fast Connectors SC / APC", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-138", name: "Tenda Aop 1200", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-139", name: "Fast Connectors SC / UPC", category: "Fibre connectivity", unit: "Each", status: "In stock" },
  { sku: "ECA-140", name: "Tenda Extender T10", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-141", name: "FAT 1 By 16 Core Loaded SC UPC Outdoor", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-142", name: "Tenda F3", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-143", name: "FAT 1 By 16 Empty", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-144", name: "Tenda F6", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-145", name: "FAT 1 By 24 Empty Outdoor With Trays", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-146", name: "Tenda Switch 5 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-147", name: "FAT 1 By 32 With Splitter SC UPC Outdoor Black", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-148", name: "Tenda Switch 8 Port", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-149", name: "FAT 1 By 8 Empty", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-150", name: "Tenda T10 Range Extender", category: "Tools and consumables", unit: "Each", status: "In stock" },
  { sku: "ECA-151", name: "FAT 1 By 8 Loaded", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-152", name: "Tension Clamp PA1500", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-153", name: "FAT 1*4 Empty White", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-154", name: "Tension Clamp PA2000", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-155", name: "FAT 1:32 Loaded Sc/upc", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-156", name: "Tension Clamp PA500", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-157", name: "FAT 1BY4 Empty", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-158", name: "Universal Pole Bracket (UPB)", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-159", name: "FAT 24 Core Onsite", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-160", name: "Wooden Climbers With Straps", category: "Aerial hardware", unit: "Each", status: "In stock" },
  { sku: "ECA-161", name: "FAT 24 Core SC UPC Pigtails Indoor", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-162", name: "XPON HG8546M Router Single Band", category: "Active networking", unit: "Each", status: "In stock" },
  { sku: "ECA-163", name: "FAT 24 Core SC UPC Pigtails Outdoor", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-164", name: "FAT 24C Empty Outdoor With Trays", category: "Enclosures and termination", unit: "Each", status: "In stock" },
  { sku: "ECA-165", name: "FIBER Cabinet 288 Core", category: "Enclosures and termination", unit: "Each", status: "In stock" },
];
